#!/usr/bin/env bats

setup() {
  export PATH="$(pwd)/tests/research-engine/mock-bin:$PATH"
  SLUG="2026-05-23-spec-test-fixture"
  TARGET="research/${SLUG}"
  mkdir -p "${TARGET}"
  cat > "${TARGET}/README.md" <<EOF
# Test fixture for /spec
Generated by spec.test.sh setup.
EOF
  cat > "${TARGET}/intent.json" <<'JSON'
{ "purpose": "test", "focus": "scenarios generation", "audience_level": "engineer", "notes": "" }
JSON
}

teardown() {
  rm -rf "research/2026-05-23-spec-test-fixture"
}

@test "spec script exists and is executable" {
  [ -x scripts/spec_generate.sh ]
}

@test "spec rejects missing slug" {
  run scripts/spec_generate.sh
  [ "$status" -ne 0 ]
  [[ "$output" == *"slug required"* ]]
}

@test "spec rejects non-existent slug" {
  run scripts/spec_generate.sh "nope-doesnt-exist"
  [ "$status" -ne 0 ]
  [[ "$output" == *"README.md"* ]]
}

@test "spec generates scenarios.json with valid schema + _meta + spec.md" {
  run scripts/spec_generate.sh "2026-05-23-spec-test-fixture"
  [ "$status" -eq 0 ]
  [ -f "research/2026-05-23-spec-test-fixture/spec/scenarios.json" ]
  [ -f "research/2026-05-23-spec-test-fixture/spec/spec.md" ]
  jq -e '._meta.source_intent_hash' "research/2026-05-23-spec-test-fixture/spec/scenarios.json"
  jq -e '.scenarios | length >= 3' "research/2026-05-23-spec-test-fixture/spec/scenarios.json"
}

@test "spec writes runs/<ISO>/log.jsonl" {
  scripts/spec_generate.sh "2026-05-23-spec-test-fixture"
  ls research/2026-05-23-spec-test-fixture/spec/runs/ | grep -q '^[0-9]'
}
