#!/usr/bin/env bats

SLUG="2026-05-23-spec-test-fixture"
TARGET="research/${SLUG}"

setup() {
  export PATH="$(pwd)/tests/research-engine/mock-bin:$PATH"
  mkdir -p "${TARGET}"
  cat > "${TARGET}/README.md" <<EOF
# Test fixture for /spec
Generated by spec.test.sh setup.
EOF
  cat > "${TARGET}/intent.json" <<'JSON'
{ "purpose": "test", "focus": "scenarios generation", "audience_level": "engineer", "notes": "" }
JSON
}

teardown() {
  rm -rf "${TARGET}"
}

@test "spec script exists and is executable" {
  [ -x scripts/spec_generate.sh ]
}

@test "spec rejects missing slug" {
  run scripts/spec_generate.sh
  [ "$status" -ne 0 ]
  [[ "$output" == *"slug required"* ]]
}

@test "spec rejects non-existent slug" {
  run scripts/spec_generate.sh "nope-doesnt-exist"
  [ "$status" -ne 0 ]
  [[ "$output" == *"README.md"* ]]
}

@test "spec generates scenarios.json with valid schema + _meta + spec.md" {
  run scripts/spec_generate.sh "${SLUG}"
  [ "$status" -eq 0 ]
  [ -f "${TARGET}/spec/scenarios.json" ]
  [ -f "${TARGET}/spec/spec.md" ]
  jq -e '._meta.source_intent_hash' "${TARGET}/spec/scenarios.json"
  jq -e '.scenarios | length >= 3' "${TARGET}/spec/scenarios.json"
}

@test "spec writes runs/<ISO>/log.jsonl" {
  run scripts/spec_generate.sh "${SLUG}"
  [ "$status" -eq 0 ]
  ls "${TARGET}/spec/runs/" | grep -q '^[0-9]'
}
